### ISSUE TITLE
It dont work yo

### ISSUE THREAD

**Issue by Nahid5** [GeneralTesler/quiver#1]
/\___/\  
|       | Quiver
 \     /  
  |___|   @2xxeformyshirt
 

Traceback (most recent call last):
  File "quiver.py", line 190, in <module>
    main(args)
  File "quiver.py", line 129, in main
    hunter = HunterManager(args)
  File "quiver.py", line 56, in __init__
    self.apikey = HunterKey(args['apikey'],kt)
NameError: global name 'kt' is not defined

**Comment by GeneralTesler** [comment]
Fixed in d2ec8fe41caf5df663441a6f1a075abe6f783978
